### ISSUE TITLE
apcu_bc issue with recent installation

### ISSUE THREAD

**Issue by kayintveen** [weprovide/valet-plus#273]
This issue refers closely to #271 .

In short, im not able to pecl install apcu_bc. it gives issues like:
`/private/tmp/pear/temp/apcu/apc_sma_api.h:85:19: note: previous declaration is here
PHP_APCU_API void apc_sma_init(`

After using the solution from #271 (installing apcu 5.1.14) apcu_bc can be installed next to it.
But after completion i still get `call to undefined function apcu_fetch()` error on page visit. 

When i check my linked brew php info i do see the following:

```
apc
APC Compatibility => 1.0.4
APCu Version => 5.1.14
Build Date => Dec  8 2018 18:02:06
 
apcu
APCu Support => Disabled
Version => 5.1.14
APCu Debugging => Disabled
MMAP Support => Enabled
MMAP File Mask => /tmp/apc.XXXXXX
Serialization Support => Disabled
Build Date => Dec  8 2018 18:01:29
```

Just checked it with a working install on a colleague's mac and all looks the same (except he runs on 5.1.11, trying that now)

Also double, triple checked that both CLI and browser version of php is the brew php@7.1 version. 
```
 ✝  /usr/local/bin  ps -efw | grep php-fpm
  501 36494     1   0 Sat12PM ??         0:01.31 /usr/local/opt/php@7.1/sbin/php-fpm --nodaemonize
  501 36503 36494   0 Sat12PM ??         0:00.17 /usr/local/opt/php@7.1/sbin/php-fpm --nodaemonize
  501 36504 36494   0 Sat12PM ??         0:00.15 /usr/local/opt/php@7.1/sbin/php-fpm --nodaemonize
```

**Comment by Prkns** [comment]
I was having the same issues as you and then followed the manual apcu install process and still had the `call to undefined function apcu_fetch()` when trying to access a local site. I restarted, y'know because why not... and it seemed to fix it.

Your mileage may vary but give it a go... There seems to be a number of issues that are fixed with a quick restart as i read it allows multiple processes to die.

**Comment by kayintveen** [comment]
Ok i have to say the following worked for me.

1. Install `pecl install apcu-5.1.14` manual
2. install via normal `valet fix && valet install`
3. Rebooted and all worked. 

Without rebooting the cli and everything seemed to work but the webserver somehow did not restart or something. even with all restarting valet restart brew restart and so on did not fix it. 

hard rebooted solved!
